# fly.toml app configuration file generated for portabilis-challenge on 2025-07-26T03:27:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portabilis-challenge'
primary_region = 'gig'
console_command = '/rails/bin/rails console'

[build]

[env]
PORT = '3000'
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"

[processes]
app = './bin/rails server'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
