# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portabilis_challenge_development

test:
  <<: *default
  database: portabilis_challenge_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: portabilis_challenge_production
    username: portabilis_challenge
    password: <%= ENV["PORTABILIS_CHALLENGE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: portabilis_challenge_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: portabilis_challenge_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: portabilis_challenge_production_cable
    migrations_paths: db/cable_migrate
